version: "3.8"

networks: 
  my-network:
# SERVICES #
services:
# Nginx #
  my-nginx:
    container_name: my-nginx
    build: ./requirements/nginx
    image: my-nginx-img
    restart: always
    volumes: 
    #- /home/$USER/data/wordpress:/var/www/wordpress
    - /Users/josephcheel/data/wordpress:/var/www/wordpress
    ports:
      - 443:443
    env_file: .env
    environment:
      - NGINX_HOST=$DOMAIN_NAME
      - NGINX_PORT=443
    networks:
        - my-network
# Wordpress #
  my-wordpress:
    container_name: my-wordpress
    build: ./requirements/wordpress
    image: my-wordpress-img
    restart: always
    volumes: 
     #- /home/$USER/data/wordpress:/var/www/wordpress
     - /Users/josephcheel/data/wordpress:/var/www/wordpress
    env_file: .env
    environment:
      - DB_NAME=$MARIADB_DB_NAME
      - DB_USER=$MARIADB_USER
      - DB_PASSWORD=$MARIADB_USER_PASSWORD
    networks:
      - my-network
# Mariadb #
  my-mariadb:
    container_name: my-mariadb
    build: ./requirements/mariadb
    image: my-mariadb-img
    restart: always
    volumes: 
    #- /home/$USER/data/mariadb:/path/to/mariadb
    -  /Users/josephcheel/data/mariadb:/var/lib/mysql
    env_file: .env
    environment:
      - MARIADB_DB_NAME=$MARIADB_DB_NAME
      - MARIADB_ROOT=$MARIADB_ROOT
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_USER_PASSWORD=$MARIADB_USER_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    networks:
        - my-network

# VOLUMES #
# volumes:
#   wordpress-volume:
#     external:
#       name: wordpress-v
#       driver: local
#       driver_opts:
#         type: none
#         device: /etc/data/wordpress
#         o: bind
  # mariadb-volume:
  #   external:
  #     name: mariadb-v
  #     driver: local
  #     driver_opts:
  #         type: none
  #         device: /path/on/host
  #         o: bind
  
# NETWORKS #

