version: "3.8"

# SERVICES #
services:
# Nginx #
  my-nginx:
    container_name: my-nginx
    build: ./requirements/nginx
    image: my-nginx-img
    restart: always
    volumes: 
    - /home/$USER/data/wordpress:/var/www/wordpress
    ports:
      - 443:443
    env_file: .env
    environment:
      - NGINX_HOST=$DOMAIN_NAME
      - NGINX_PORT=443
    networks:
        - my-network
# Wordpress #
  my-wordpress:
    container_name: my-wordpress
    build: ./requirements/wordpress
    image: my-wordpress-img
    volumes: 
     - /home/$USER/data/wordpress:/var/www/wordpress
     #- /etc/data/wordpress:/path/to/wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$DOMAIN_NAME
      - WORDPRESS_DB_USER=$USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    networks:
      - my-network
# Mariadb #
  my-mariadb:
    container_name: my-mariadb
    build: ./requirements/mariadb
    image: my-mariadb-img
    restart: always
    volumes: 
    - /home/$USER/data/mariadb:/path/to/mariadb
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MARIADB_USER=$MARIADB_USER
      - MYSQL_ROOT_PASSWORD=$MARIADB_PASSWORD
    networks:
        - my-network

# VOLUMES #
# volumes:
#   wordpress-volume:
#     external:
#       name: wordpress-v
#       driver: local
#       driver_opts:
#         type: none
#         device: /etc/data/wordpress
#         o: bind
  # mariadb-volume:
  #   external:
  #     name: mariadb-v
  #     driver: local
  #     driver_opts:
  #         type: none
  #         device: /path/on/host
  #         o: bind
  
# NETWORKS #
networks: 
  my-network:
    driver: bridge
